# Generated by Django 4.2.30 on 2026-08-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='RoomRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=512, unique=True)),
                ('room_password', models.CharField(blank=True, default='', max_length=255)),
                ('admin_password', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to='main.appuserrecord')),
            ],
            options={
                'verbose_name': '部屋',
                'verbose_name_plural': '部屋',
                'ordering': ['room_password', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_list_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to='main.appuserrecord')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='main.roomrecord')),
            ],
            options={
                'verbose_name': 'リスト',
                'verbose_name_plural': 'リスト',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(blank=True, default='', max_length=64)),
                ('purchase_status', models.CharField(blank=True, default='todo', max_length=32)),
                ('purchased', models.BooleanField(default=False)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.shoppinglistrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to='main.appuserrecord')),
            ],
            options={
                'verbose_name': 'アイテム',
                'verbose_name_plural': 'アイテム',
                'ordering': ['shopping_list__name', 'position', 'name', 'id'],
                'unique_together': {('shopping_list', 'source_item_id')},
            },
        ),
    ]
